# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ef5132f04947fa3c051c46cde86968e621ef8e83fd4462ef695ba6210f73f80045ef75ef45984a8567b8ab27ddd257e61ffa740cd87a067a035450e31b413b40

test:
  secret_key_base: 689d8f2eb59b3bf202b711e7671913597c5e6f1a07c7b5b8bc9fca75ba23717ed27540ebc82d8775c7d2465bc7bc086f6c5d35aef0052672b89d752640d544e4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
